spring:
  application:
    name: collector

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

api:
  tradingeconomics:
    key: ${TRADING_ECONOMICS_API_KEY}
  fred:
    key: ${FRED_API_KEY}
