name: Deploy ETL

on:
  push:
    branches:
      - main

jobs:
  deploy-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t kimdongjae/hotsignal-etl:latest .

      - name: Push Docker image
        run: docker push kimdongjae/hotsignal-etl:latest

      - name: Deploy to ETL server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_ETL }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ secrets.SSH_PROXY_HOST }}
          proxy_username: ${{ secrets.SSH_PROXY_USER }}
          proxy_key: ${{ secrets.SSH_PROXY_KEY }}
          script: |
            echo "🧹 Cleaning up old ETL container..."
            docker rm -f hotsignal-etl || true

            echo "🔍 Checking for any container using port 5001..."
            CONTAINER_ID=$(docker ps -q --filter "publish=5001")
            if [ ! -z "$CONTAINER_ID" ]; then
              echo "⚠️ Port 5001 is occupied by $CONTAINER_ID. Stopping it..."
              docker stop $CONTAINER_ID
              docker rm $CONTAINER_ID
            fi

            echo "📦 Pulling latest image..."
            docker pull kimdongjae/hotsignal-etl:latest

            echo "🚀 Running ETL container..."
            docker run -d -p 5001:5001 \
              --name hotsignal-etl \
              kimdongjae/hotsignal-etl:latest
