name: Deploy ETL

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t kimdongjae/hotsignal-etl:latest .

      - name: Push Docker image
        run: docker push kimdongjae/hotsignal-etl:latest

      - name: Deploy to ETL server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_ETL }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ secrets.SSH_PROXY_HOST }}
          proxy_username: ${{ secrets.SSH_PROXY_USER }}
          proxy_key: ${{ secrets.SSH_PROXY_KEY }}
          script: |
            echo "🔍 Stopping existing container if running..."
            docker rm -f hotsignal-etl || true

            echo "📦 Pulling latest image..."
            docker pull kimdongjae/hotsignal-etl:latest

            echo "🚀 Running ETL container..."
            docker run -d -p 5001:5001 \
              --name hotsignal-etl \
              kimdongjae/hotsignal-etl:latest
